### ISSUE TITLE
mt-max-hide and mt-med-hide aren't hiding at small widths

### ISSUE THREAD

**Issue by trungly** [pmdesgn/mt.css#3]
Either I'm really confused or there is a bug with the way mt-max-hide and mt-med-hide works.  mt-max-hide still shows at medium and min widths, and mt-med-hide still shows at min widths.  The reason I think it's a bug is because mt-max-show and mt-med-show do what they are intended to do ("show") at the mid and min ranges.

I'm trying on Chrome on an initially full screen 13" Macbook Pro.

**Comment by pmdesgn** [comment]
Hmm, yes the hide/show behavior seems incorrect. I "cleaned up" the responsive SCSS before publishing, must've broken it. Good catch, thanks -- will look into it.

**Comment by pmdesgn** [comment]
I've now redone those classes to work more "logically". Also, you can now control whether to show as block, inline, or inline-block. See updated docs.
